### PR TITLE
Prepare for 2.8 release

### PR DESCRIPTION
**Pull request by zachcp**
- add a Makefile for creating unbundled CDK jar files
- use sed to remove large, unused JARs
- manually add Google guava which is a hidden dep in rCDK code (used in several locations so removing might cause breaks)
- bumpversion
- ref https://github.com/cdk/cdk/issues/911
- ref https://github.com/cdk/cdk/issues/915#issuecomment-1251402953
- size ~27Mb (similar to previous)

### CODE REVIEW

**Comment by johnmay** [comment]
Ah I would do this with a little maven stub project :). But sure sed works as well

**Comment by rajarshi** [comment]
Probably worth seeing if we can get rid of the Guava dep. - it was mainly for convenience

**Comment by johnmay** [comment]
I got rid of Guava in CDK in 2.7 I think, do you use this independently?

**Comment by zachcp** [comment]
When I took Guava out of rcdklibs, the rcdk tests failed. Its at least used [here](https://github.com/CDK-R/cdkr/blob/master/rcdkjar/src/org/guha/rcdk/view/RcdkDepictor.java#L3-L4). @rajarshi if you refactor that in the 2.8 branch of rcdk, I can update the libs to remove guava.

**Comment by johnmay** [comment]
The mulitmap is easy to replace, since 1.8: map.computeIfAbsent(key, k -> new ArrayList<>());

**Comment by zachcp** [comment]
thanks, John.   I modified that file based on your suggestion (PR [here](https://github.com/CDK-R/cdkr/pull/133); eyeballs welcome) and removed Guava here.   If things look good to you both I can move forward with submitting a new release of both packages.

**Review by rajarshi — APPROVED** [review]

**Comment by zachcp** [comment]
@rajarshi can you squash merge this (or give me write access)

**Comment by rajarshi** [comment]
Just merged it. Also happy to give you write access - where do I set that?

**Comment by zachcp** [comment]
You can set permission levels for individuals or groups within GitHub Settings. 


image

**Comment by rajarshi** [comment]
OK, you're an admin now, so i think that gives yiou write access to everything

**Pull request merged**
